# Generated by Django 4.1.5 on 2023-01-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Jeans', 'Jeans'), ('Shoes', 'Shoes'), ('Socks', 'Socks'), ('Hoddie', 'Hoodie')], max_length=50)),
            ],
            options={
                'verbose_name': 'Mens SubCategory',
                'verbose_name_plural': 'Mens SubCategories',
            },
        ),
        migrations.CreateModel(
            name='WomensSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Jeans', 'Jeans'), ('Shoes', 'Shoes'), ('Socks', 'Socks'), ('Hoddie', 'Hoodie')], max_length=50)),
            ],
            options={
                'verbose_name': 'Womens SubCategory',
                'verbose_name_plural': 'Womens SubCategories',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_men',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.menssubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_woemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.womenssubcategory'),
        ),
    ]
