# Generated by Django 4.1.5 on 2023-01-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_customer_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WomensSubCategory',
            new_name='Subcategory',
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory_woemen',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_men',
        ),
        migrations.DeleteModel(
            name='MensSubCategory',
        ),
    ]
