# Generated by Django 4.1.5 on 2023-01-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='clothes_size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.PositiveIntegerField(blank=True, choices=[(39, 39), (40, 40), (41, 41), (42, 42), (42, 42)], null=True),
        ),
    ]
